- name: Install Anubis
  hosts: nuculabs
  become: true
  become_method: sudo
  vars_files:
    - variables.yaml
  tasks:
    - name: Setup Container
      block:
        - name: Ensure Podman is installed
          ansible.builtin.package:
            name: podman
            state: present
        - name: Pull image
          containers.podman.podman_image:
            name: "{{ anubis.container_image }}"
            state: present
        - name: "Copy container"
          ansible.builtin.template:
            src: ./templates/container/anubis.container.j2
            dest: "/etc/containers/systemd/anubis_{{ anubis.instance_name }}.container"
            mode: "0644"
        - name: Reload systemd
          ansible.builtin.command:
            cmd: systemctl daemon-reload
        - name: Stop service
          ansible.builtin.systemd_service:
            name: "anubis_{{ anubis.instance_name }}.service"
            state: stopped
            enabled: true
        - name: Enable service
          ansible.builtin.systemd_service:
            name: "anubis_{{ anubis.instance_name }}.service"
            state: started
            enabled: true
    - name: Setup firewall
      block:
        - name: Create firewalld service
          ansible.builtin.template:
            src: ./templates/firewall/anubis.xml.j2
            dest: "/etc/firewalld/services/anubis_{{ anubis.instance_name }}.xml"
            mode: "0644"
        - name: Reload firewalld
          ansible.builtin.command:
            argv:
              - firewall-cmd
              - --reload
        - name: Enable firewalld service
          ansible.posix.firewalld:
            service: "anubis_{{ anubis.instance_name }}"
            state: enabled
            permanent: true
            immediate: true
            offline: true
      when: setup_firewall
    - name: Setup firewall for metrics
      block:
        - name: Create firewalld service
          ansible.builtin.template:
            src: ./templates/firewall/anubis_metrics.xml.j2
            dest: "/etc/firewalld/services/anubis_metrics_{{ anubis.instance_name }}.xml"
            mode: "0644"
        - name: Reload firewalld
          ansible.builtin.command:
            argv:
              - firewall-cmd
              - --reload
        - name: Enable firewalld service
          ansible.posix.firewalld:
            service: "anubis_metrics_{{ anubis.instance_name }}"
            state: enabled
            permanent: true
            immediate: true
            offline: true
      when: setup_firewall_for_metrics
