- name: Install Forgejo
  hosts: nuculabs
  become: true
  become_method: sudo
  vars_files:
    - variables.yaml
  tasks:
    # Create necessary directories.
    - name: "Create directories"
      block:
        - name: Create base directory
          ansible.builtin.file:
            path: "{{ forgejo.base_directory }}"
            state: directory
            mode: "0755"
          ignore_errors: true
    - name: Setup Container
      block:
        - name: Ensure Podman is installed
          ansible.builtin.package:
            name: podman
            state: present
        - name: Pull image
          containers.podman.podman_image:
            name: "{{ forgejo.container_image }}"
            state: present
        - name: "Copy container"
          ansible.builtin.template:
            src: ./templates/container/forgejo.container.j2
            dest: /etc/containers/systemd/forgejo.container
            mode: "0644"
        - name: Reload systemd
          ansible.builtin.command:
            cmd: systemctl daemon-reload
        - name: Stop service
          ansible.builtin.systemd_service:
            name: forgejo.service
            state: stopped
            enabled: true
        - name: Enable service
          ansible.builtin.systemd_service:
            name: forgejo.service
            state: started
            enabled: true
    - name: Setup firewall
      block:
        - name: Create firewalld service
          ansible.builtin.template:
            src: ./templates/firewall/forgejo.xml.j2
            dest: /etc/firewalld/services/forgejo.xml
            mode: "0644"
        - name: Reload firewalld
          ansible.builtin.command:
            argv:
              - firewall-cmd
              - --reload
        - name: Enable firewalld service
          ansible.posix.firewalld:
            service: forgejo
            state: enabled
            permanent: true
            immediate: true
            offline: true
      when: setup_firewall
